sudo: required
language: node_js
node_js:
- '0.12'
before_install:
- curl https://install.meteor.com/ | sh
- npm install -g mupx

services: mongodb
script:
- meteor --test --release velocity:METEOR@1.1.0.2_3
