sudo: required
language: node_js
node_js:
- '0.12'
before_install:
- curl https://install.meteor.com/ | sh
- npm install -g mupx

- openssl aes-256-cbc -K $encrypted_57efc54cf7a8_key -iv $encrypted_57efc54cf7a8_iv
  -in secrets.tar.enc -out secrets.tar -d  # Decrypt secrets.tar.enc
- tar xvf secrets.tar # Decompress secrets.tar
services: mongodb
script:
- meteor --test --settings settings.json --release velocity:METEOR@1.1.0.2_3
after_success:
- curl http://git.io/vqbln | sh
